### ISSUE TITLE
Report encrypted document in return value

### ISSUE THREAD

**Issue by TomTasche** [ViliusSutkus89/wvWare-Android#4]
The (upstream) library currently reports -1 for all kinds of errors, including a missing password for encrypted documents. I need a dedicated return value that tells me to prompt the user for a password.

Password-encrypted document attached for testing.
[toc.doc.zip](https://github.com/ViliusSutkus89/wvWare-Android/files/4080141/toc.doc.zip)

**Comment by ViliusSutkus89** [comment]
Available in wvWare-Android v1.2.4
